dist: trusty

language: csharp
mono: none
dotnet: 2.2.300

addons:
  sonarcloud:
    organization: "lholota" # the key of the org you chose at step #3
    token:
      secure: asdhofhioshadshifhso

jobs:
  include:
    - stage: Build
      script: 
        - dotnet build -c Release -p:Version=1.0.$TRAVIS_BUILD_NUMBER
    - stage: Unit tests
      script:
        -  dotnet test -c Release --no-build --no-restore -p:Version=1.0.$TRAVIS_BUILD_NUMBER --logger "trx" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - stage: Code analysis
      script:
        - sonar-scanner
    - stage: Deploy
      if: branch = master
      script:
        - dotnet nuget push src/LH.Dhcp/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json