dist: bionic

language: csharp
mono: none
dotnet: 2.2
jdk: openjdk8

git:
  depth: false

script: 
  - dotnet tool install --global dotnet-sonarscanner
  - export PATH="~/.dotnet/tools:$PATH"

  - | 
      dotnet sonarscanner begin \
        /k:"lholota_dhcp-dotnet" \
        /o:lholota \
        /d:sonar.host.url=https://sonarcloud.io \
        /d:sonar.login=$SONARCLOUD_TOKEN \
        /d:"sonar.cs.vstest.reportsPaths=$TRAVIS_BUILD_DIR/src/**/TestResults/*.trx" \
        /d:"sonar.cs.opencover.reportsPaths=$TRAVIS_BUILD_DIR/src/**/coverage.opencover.xml" \
        /d:"sonar.scm.revision=$TRAVIS_COMMIT" \
        /d:"sonar.links.scm=https://github.com/lholota/dhcp-dotnet" \
        /d:"sonar.branch.name=$TRAVIS_BRANCH"

  - cd src
  - dotnet build -c Release -p:Version=1.0.$TRAVIS_BUILD_NUMBER

  - |
      dotnet test -c Release --no-build --no-restore \
        -p:Version=1.0.$TRAVIS_BUILD_NUMBER \
        --logger "trx" \
        /p:CollectCoverage=true \
        /p:CoverletOutputFormat=opencover

  - dotnet sonarscanner end /d:sonar.login=$SONARCLOUD_TOKEN

# deploy:
#   provider: script
#   on:
#     branch: master
#   script: dotnet nuget push src/LH.Dhcp/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json