dist: bionic

language: csharp
mono: none
dotnet: 2.2
jdk: openjdk8

git:
  depth: false

script: 
  - ./build/travis-build.sh

# deploy:
#   provider: script
#   on:
#     branch: master
#   script: dotnet nuget push src/LH.Dhcp/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json